mydbtprofile:
    target: dev
    outputs:
        dev:
            type: bigquery
            method: oauth
            project: newsaggregationproject
            dataset: dbt_dataset # You can also use "schema" here
            threads: 4 # Must be a value of 1 or greater 
            